# Numpy

In [1]:
## Numpy Array

In [2]:
# 리스트와 넘파이 어레이 속도 비교
import numpy as np 
np_arr = np.arange(100000)
nu_list = [i for i in range(100000)]


In [3]:
%%time
for i in range(100):
    sum(nu_list)

Wall time: 150 ms


In [4]:
%%time
for i in range(100):
    sum = 0
    np.sum(np_arr)

Wall time: 6 ms


## 1차원 배열 만들기

In [5]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(ar)

numpy.ndarray

In [7]:
ar.shape

(10,)

## 백터화 연산

In [12]:
al = [2 * i for i in range(1, 11)]
al

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [13]:
2 * ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
2 * al

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [15]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [16]:
2 * a + b

array([12, 24, 36])

In [17]:
a == 2

array([False,  True, False])

In [18]:
b > 15

array([False,  True,  True])

In [20]:
(a == 2) & (b > 10)

array([False,  True, False])

## 2차원 배열 만들기

In [21]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
c.shape

(2, 3)

In [23]:
 len(c), len(c[0])

(2, 3)

In [24]:
np.arange(10, 90)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

### 3차원 함수 만들기

In [29]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [30]:
d.shape, d.ndim

((2, 3, 4), 3)

## 배열의 인덱싱

In [31]:
a = np.array([0, 1, 2, 3, 4])
a[2]

2

In [32]:
a[-1]

4

In [35]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a[1, 0]

3

## 배열 슬라이싱

In [39]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [40]:
a[:, 1:3]

array([[1, 2],
       [5, 6]])

In [48]:
a = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
a[1, 2]

7

In [57]:
a[2, 4]

14

In [58]:
# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.

In [ ]:
# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.

In [ ]:
# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

## 배열 인덱싱

In [62]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [63]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [64]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [65]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [66]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [67]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [69]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [71]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [77]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
idx = np.array([2,5,8,11,14,17,20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [74]:
x % 4

array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0],
      dtype=int32)