# 배열연산

In [1]:
import numpy as np 
np_arr = np.arange(100000)
nu_list = [i for i in range(100000)]

## 벡터화 연산

In [2]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [3]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 5.99 ms


In [4]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [5]:
%%time
z = x + y

Wall time: 0 ns


In [6]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [7]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [8]:
a ==  b

array([False,  True, False,  True])

In [9]:
a >= b

array([False,  True,  True,  True])

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [11]:
np.all(a == b)

False

In [12]:
np.all(a == c)

True

In [13]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [14]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [15]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [16]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

## 스칼라와 벡터/행렬의 곱셈

In [19]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [21]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## 브로드캐스팅

In [23]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [24]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [25]:
x + y

array([1, 2, 3, 4, 5])

In [26]:
x + 1

array([1, 2, 3, 4, 5])

In [27]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [28]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [29]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [30]:
y = np.arange(3)
y

array([0, 1, 2])

In [31]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

## 차원 축소 연산

In [32]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [33]:
np.sum(x)

6

In [35]:
np.sum(x, axis=0)

array([3, 3])

In [36]:
np.sum(x, axis=1)

array([2, 4])

In [39]:
# 연습문제
x = np.linspace(1.0, 10.0, 30).reshape(5, 6)
x

array([[ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
         2.55172414],
       [ 2.86206897,  3.17241379,  3.48275862,  3.79310345,  4.10344828,
         4.4137931 ],
       [ 4.72413793,  5.03448276,  5.34482759,  5.65517241,  5.96551724,
         6.27586207],
       [ 6.5862069 ,  6.89655172,  7.20689655,  7.51724138,  7.82758621,
         8.13793103],
       [ 8.44827586,  8.75862069,  9.06896552,  9.37931034,  9.68965517,
        10.        ]])

In [44]:
x.sum()

165.0

In [43]:
x.sum(axis=1)

array([10.65517241, 21.82758621, 33.        , 44.17241379, 55.34482759])

29

## 정렬

In [47]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [48]:
np.sort(a)  # axis=-1 또는 axis=1 과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [49]:
np.sort(a, axis=1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [50]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [51]:
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [52]:
a.sort()

In [53]:
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])