# 난수 발생과 카운팅

In [1]:
import numpy as np

## 시드 설정하기

In [2]:
np.random.rand(5)

array([0.47715299, 0.80969969, 0.96351763, 0.14774156, 0.58082874])

In [3]:
np.random.rand(5)

array([0.92626156, 0.7591026 , 0.90358113, 0.73438825, 0.487587  ])

In [4]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

In [5]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

## 데이터의 순서 바꾸기

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.random.shuffle(x)
x

array([5, 7, 6, 4, 3, 1, 2, 8, 9, 0])

## 데이터 샘플링

In [8]:
np.random.choice(5, 5, replace=False)  # shuffle 명령과 같다.

array([4, 0, 1, 2, 3])

In [10]:
np.random.choice(5, 5, replace=True)

array([1, 2, 1, 2, 4])

In [11]:
np.random.choice(5, 3, replace=False)  # 3개만 선택

array([3, 1, 0])

In [12]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  # 선택 확률을 다르게 해서 10개 선택

array([2, 0, 3, 3, 3, 3, 3, 3, 2, 3])

## 난수 생성

In [15]:
np.random.rand(5)

array([0.44467178, 0.11104748, 0.53702586, 0.32579935, 0.86519536])

In [16]:
np.random.randn(10)

array([-0.33764227, -0.12044229,  1.27944955, -0.49866644,  1.04592685,
        0.38428501,  0.73694653,  0.05222718, -0.59212641,  1.88113822])

In [17]:
np.random.randint(10, size=10)

array([1, 3, 7, 7, 2, 5, 0, 0, 8, 3])

In [18]:
np.random.randint(10, 20, size=10)

array([16, 13, 14, 16, 19, 15, 12, 14, 13, 10])

In [20]:
x = np.random.randn(250) * 100 + 10000
x[:10]

array([ 9957.84321675,  9929.99815237, 10001.61135008,  9993.85957591,
        9964.62971213,  9948.85940894, 10035.17252153,  9904.04318226,
       10062.65927608,  9934.95197094])

In [23]:
price = 10000
tomorrow = price * (1 + np.random.randn(1)/100.)
tomorrow[0]

9969.448595008358

In [26]:
# 연습문제 3.5.2
prices = []
price = 10000
for i in range(250):
    tmp = price * (1 + np.random.randn(1)/100.)
    price = tmp[0]
    prices.append(price)
prices[:10]

[10002.507873690509,
 10034.685574381976,
 10035.199396961043,
 10092.585855960619,
 9907.222036594552,
 9846.093335619067,
 9780.854465544733,
 9852.198590155078,
 9767.484272419606,
 9606.787260182658]

# 정수 데이터 카운팅

In [27]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [28]:
a = np.array(['a', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [29]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [30]:
count

array([2, 1, 1], dtype=int64)

In [31]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)