# 메트릭스 곱셈

In [1]:
import numpy as np

## 벡터와 벡터의 곱셈

In [4]:
x = np.arange(1, 4).reshape(3, 1)
x

array([[1],
       [2],
       [3]])

In [5]:
y = np.arange(4, 7).reshape(3, 1)
y

array([[4],
       [5],
       [6]])

In [6]:
x.shape, y.shape

((3, 1), (3, 1))

In [7]:
x.T.shape

(1, 3)

In [8]:
z = x.T @ y
z

array([[32]])

In [9]:
z.shape

(1, 1)

In [10]:
z[0, 0]

32

In [11]:
np.dot(x.T, y)

array([[32]])

In [12]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
x @ x.T

array([[14, 32],
       [32, 77]])

In [15]:
y = x.T

In [16]:
def mat_mul(x, y):
    z = np.zeros((len(x), len(y[0])))
    if len(x[0]) != len

for i in range(len(x)):
    for k in range(len(y[0])):
        val = 0
        for m in range(len(x[0])):
            val += x[i, k] * y[k, m]
        print(val)
        

5
14
27
20
35
54


In [17]:
np.dot(x, y)

array([[14, 32],
       [32, 77]])

In [19]:
x = np.array([[100], [80], [50]])
y = np.array([[3], [4], [5]])

x.T @ y

array([[870]])