In [1]:
# 1.길이가 10인 0-벡터를 만드세요

In [2]:
import numpy as np

In [3]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요

In [5]:
a = np.zeros(10)
a[5] = 1
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [6]:
# 3. 10 부터 49까지의 값을 가지는 벡터를 만드세요

In [7]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
# 4. 위 벡터의 순서를 바꾸세요

In [9]:
x = x[::-1]
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [10]:
# 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요

In [11]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
# 6. 벡터 [1, 2, 0, 0, 4, 0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요

In [13]:
x = np.array([1, 2, 0, 0, 4, 0])
x > 0

array([ True,  True, False, False,  True, False])

In [14]:
x[x > 0]

array([1, 2, 4])

In [15]:
# 7. 3x3 단위행렬을 만드세요

In [16]:
x = np.identity(n=3, dtype=np.int8)
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [17]:
# 8. 난수 원소를 가지는 3x3 행렬을 만드세요.

In [18]:
x = np.random.randint(1, 20, size=(3, 3))
x

array([[15,  6,  3],
       [12,  5, 15],
       [ 9, 15, 18]])

In [19]:
# 9. 위에서 만든 난수 행렬에서 최대값/최소갑원소를 찾으세요.

In [20]:
np.max(x)    # 최대값

18

In [21]:
np.min(x)    # 최소값

3

In [22]:
# 10. 위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [23]:
x.mean(axis=1), x.mean(axis=0)

(array([ 8.        , 10.66666667, 14.        ]),
 array([12.        ,  8.66666667, 12.        ]))